# tag.yml v1.2
# 1.2 - Fix tag search.
# 1.1 - Define DOTNET_SKIP_FIRST_TIME_EXPERIENCE/NUGET_XMLDOC_MODE.
# 1.0 - Initial release.

name: Tag

on:
  - push

env:
  CI: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
  NUGET_XMLDOC_MODE: 'skip'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Dump context
      env:
        CONTEXT: ${{ toJson(github) }}
      run: |
        echo "Context: $Env:CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get existing tag
      id: existingtag
      uses: WyriHaximus/github-action-get-previous-tag@0.2.0
      continue-on-error: true

    - name: Get current version
      run: |
        dotnet tool install --global Nito.ProjProps
        echo ::set-env name=NEWTAG::v$(projprops --name version --output-format SingleValueOnly --project src --project-search)

    - name: Create tag
      if: env.NEWTAG != steps.existingtag.outputs.tag
      run: |
        git tag ${{ env.NEWTAG }}
        git push --tags
